### ISSUE TITLE
Inconsistent MAC and IPv6 format for several getters

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-ios#111]
### Description of Issue/Question

https://github.com/napalm-automation/napalm-ios/pull/110 shows that as of napalm-ios 0.6.0, the following methods need a bit of work and use the `ip` and `mac` napalm-base helpers:

- [x] get_mac_address_table, fixed in https://github.com/napalm-automation/napalm-ios/pull/110
- [x] get_arp_table, fixed in https://github.com/napalm-automation/napalm-ios/pull/110
- [x] get_interfaces
- [ ] get_lldp_neighbors
- [ ] get_lldp_neighbors_detail
- [ ] get_bgp_neighbors
- [ ] get_interfaces_ip
- [ ] get_ntp_peers
- [ ] traceroute
- [ ] ping

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
0.6.0
```

**Comment by ktbyers** [comment]
I can own this part...should improve napalm-base tests such that standardized format for mac-address, IP address is validated as part of unit tests.

**Comment by dbarrosop** [comment]
> should improve napalm-base tests such that standardized format for mac-address, IP address is validated as part of unit tests

I suggest holding a bit on this. Let's discuss it next week. I personally think we should keep the current getters in maintenance mode and focus on OC. The models have builtin type checking so we get a lot of stuff for free.

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/451
