### ISSUE TITLE
Is cntl-C a control character for TCLSH

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#112]
cntl-C is required for banner, but reports that this is causing TCLSH for inline transfer to terminate.

**Comment by bdlamprecht** [comment]
This could be a limitation of Cisco's tclsh, but I figured I would mention it.

tclsh appears to interpret multiple spaces in a row as a single space.
For example, in the "banner login" section, the following:

` ...SNIP...`
`*[3 spaces] legitimate business purposes only. The actual or attempted [6 spaces]*`
`*[3 spaces] unauthorized access, use, or modification of this system is [5 spaces]*`
` ...SNIP...`

becomes:

` ...SNIP...`
`* legitimate business purposes only. The actual or attempted *`
`* unauthorized access, use, or modification of this system is *`
` ...SNIP...`

(i.e. it removes the additional spaces).

**Comment by ktbyers** [comment]
I will test...there were definitely some nuances to TCLSH when I wrote the Netmiko inline file transfer.

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/452
