### ISSUE TITLE
Implement get_optics getter for IOS devices

### ISSUE THREAD

**Issue by kaage** [napalm-automation/napalm-ios#130]
### Description of Issue/Question

I would need to get optical rx power from Cisco 2960x and Cisco 4500x. It seems get_optics is doing just what I need but doesn't support IOS yet.

**Comment by ktbyers** [comment]
You are just saying you want this feature?

If so, you need to write a Pull Request for it.

**Comment by ktbyers** [comment]
@kaage is working on a pull-request for this.

**Comment by kaage** [comment]
I wrote pull-request for this: [134](https://github.com/napalm-automation/napalm-ios/pull/134)

**Comment by ktbyers** [comment]
Closing as we have a pending PR for this.
