### ISSUE TITLE
Add support to napalm-ios for netmiko telnet type

### ISSUE THREAD

**Issue by sorano** [napalm-automation/napalm-ios#132]
### Description of Issue/Question
Feature request:
Add support to napalm-ios to force and/or failover to netmiko telnet type.

netmiko supports telnet with the telnet device type:
`device['device_type'] = 'cisco_ios_telnet'`

https://github.com/ktbyers/netmiko/issues/159#issuecomment-245977602

**Comment by ktbyers** [comment]
@dbarrosop @mirceaulinic What are your thoughts on adding an optional_argument `ios_transport` which defaults to SSH (but also supports telnet).

I would then force the transfer mode to inline (as it would have to use the inline-transfer that uses TCL).

**Comment by dbarrosop** [comment]
> What are your thoughts on adding an optional_argument ios_transport which defaults to SSH (but also supports telnet).

+100

But call it just transport, I don't think it's `ios` specific and if we build a generic `napalm-netmiko` it might end up supporting that same optional_arg

**Comment by mirceaulinic** [comment]
Yes, i would suggest the same - i think `transport` would make more sense and could be used by few other drivers.

**Comment by mirceaulinic** [comment]
Hi @sorano - would you be able to submit a pull request with the changes required for this?
Netmiko seems to have good support for telnet so I assume it's pretty easy.
Thanks!

**Comment by mirceaulinic** [comment]
Hi @sorano - I believe this has been already implemented.

We are currently in the process of reunification, please check https://napalm-automation.net/reunification/.
Going forward, we'd like to ask you to submit Pull Requests and Issues to the main repository: https://github.com/napalm-automation/napalm.
