### ISSUE TITLE
napalm-ios will generate an error on 'dir' if not in enable mode

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#14]
```
pynet-rtr1>dir
Translating "dir"

% Bad IP address or host name
% Unknown command or computer name, or unable to find computer address
```

You only need this for the file operations and not for the getter operations.

**Comment by jzohrab** [comment]
I'm getting this error now, it can't open the device at all.  Here is a script that demonstrates the error:

```
import napalm
driver = napalm.get_network_driver('ios')
print 'ctor'
device = driver('172.16.1.124', 'admin', 'admin')
print 'opening ...'
device.open()
print 'closing ...'
device.close()
```

Brand new venv:

```
$ virtualenv venv
New python executable in /Users/jzohrab/Documents/Projects/acl_manager/venv/bin/python
Installing setuptools, pip, wheel...done.
$ source venv/bin/activate
(venv) $ pip install napalm
... [snip] ...
Installing collected packages: ... [snip] ...
Successfully installed MarkupSafe-0.23 PyYAML-3.11 bnclient-0.3 cffi-1.7.0 cryptography-1.4 enum34-1.1.6 gtextfsm-0.2.1 idna-2.1 ipaddress-1.0.16 jinja2-2.8 junos-eznc-1.3.1 lxml-3.6.0 napalm-1.1.0 napalm-base-0.14.1 napalm-eos-0.2.1 napalm-fortios-0.1.1 napalm-ibm-0.1.1 napalm-ios-0.1.7 napalm-iosxr-0.2.1 napalm-junos-0.2.1 napalm-nxos-0.2.1 napalm-panos-0.1.0 napalm-pluribus-0.2.0 ncclient-0.4.7 netaddr-0.7.18 netmiko-0.5.1 pan-python-0.9.1 paramiko-2.0.1 pexpect-4.1.0 ptyprocess-0.5.1 pyFG-0.47 pyIOSXR-0.14 pyPluribus-0.3.0 pyasn1-0.1.9 pycparser-2.14 pycsco-0.3.5 pyeapi-0.6.1 requests-2.10.0 requests-toolbelt-0.6.2 scp-0.10.2 six-1.10.0 xmltodict-0.10.2
```

Run with results:

```
(venv) ~/Documents/Projects/acl_manager$ python blah.py 
ctor
opening ...
Traceback (most recent call last):
  File "blah.py", line 6, in <module>
    device.open()
  File "/Users/jzohrab/Documents/Projects/acl_manager/venv/lib/python2.7/site-packages/napalm_ios/ios.py", line 68, in open
    self.dest_file_system = self.device._autodetect_fs()
  File "/Users/jzohrab/Documents/Projects/acl_manager/venv/lib/python2.7/site-packages/netmiko/ssh_connection.py", line 68, in _autodetect_fs
    "system: {} {}".format(cmd, output))
ValueError: An error occurred in dynamically determining remote file system: dir Translating "dir"...domain server (255.255.255.255)
 (255.255.255.255)
Translating "dir"...domain server (255.255.255.255)
```

This, or something like it, used to work back on Apr 26.  Checking code changes here. ... EDIT: actually, not really sure if that date (Apr 26) is accurate, b/c I doubt that I was destroying and recreating the venv regularly.

**Comment by ktbyers** [comment]
@jzohrab Does 'admin/admin' log you into enable mode or just level1?

You should be able to work around it by setting the file system (as an optional argument) or by logging in using enable mode.

``` python
optional_args['dest_file_system'] = 'flash:'        # or whatever is appropriate
device = driver(ip_addr, username, password, optional_args=optional_args)
```

**Comment by ktbyers** [comment]
@jzohrab The adding of auto detection of file system is what caused it to break. Now it tries to autodetect the file system which doesn't work if you are not in privilege level1.

**Comment by jzohrab** [comment]
It takes me to level1:

```
$ ssh admin@172.16.1.124
Password: 
iosv-1>        # HERE I AM
iosv-1>en
Password: 
iosv-1#
```

In Napalm, how would I log in in enable mode?

**Comment by ktbyers** [comment]
This should work:

```
# assuming 'my_device' is the name of your NAPALM object
my_device.device.secret = 'enable_secret'
my_device.device.enable()
```

**Comment by ktbyers** [comment]
Hmmm...that won't work as 'device' is not created until open().

**Comment by ktbyers** [comment]
So with current code a couple of solutions are:
1. Change AAA so user privilege is 15.

or
1. Pass in optional argument that specifies the dest_file_system

**Comment by ktbyers** [comment]
Added this issue:

https://github.com/napalm-automation/napalm-ios/issues/19

**Comment by dbarrosop** [comment]
How is this one going? It's still relevant?

**Comment by ktbyers** [comment]
This should be fixed now.

**Comment by tyagian** [comment]
For me its checking on Cisco router:
Router-1#dir
%Error opening disk0:/ (No such device)
Cisco 7200. user privilege 15 to connect ssh user to skip user mode. 
How can this be solved?

**Comment by ktbyers** [comment]
@tyagian If you set this to something:

```
optional_args['dest_file_system'] = 'bogus:'
```

Then it will no longer due the auto-detect.

Note, the NAPALM config operations won't work here, but the NAPALM getters should.

For the NAPALM config operations to work, you need a file system on the device. So you will need to create one using GNS3...I assume this is GNS3?.
