### ISSUE TITLE
Timing issue when using configure replace with inline transfer

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#144]
MD5 would fail.

Basically, it seems like the SSH session get out of sync in some way and not capture the actual MD5 output.

**Comment by ktbyers** [comment]
Fixed in Netmiko here:

https://github.com/ktbyers/netmiko/commit/3224aad45e5b93486185123f26ccaec27ce71b7b

**Comment by mirceaulinic** [comment]
@ktbyers as pre your previous comment this seems to be solved. Can we close the issue?
