### ISSUE TITLE
remove 'ip scp server enable' after deployment

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm-ios#174]
### Description of Issue/Question
during file transfer, the transfer class will configure 'ip scp server enable'; but it won't disable it. Can we put 'no ip scp server enable' after transfer finish?

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ *] Yes
- [ ] No

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
0.7.0
```

### IOS version
(Paste verbatim output from `show version` between quotes below)

```
any
```

### Steps to Reproduce the Issue
N/A
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
N/A
```

**Comment by ktbyers** [comment]
This is by design.

See comments in the PR:

https://github.com/napalm-automation/napalm-ios/pull/175
