### ISSUE TITLE
Support enable mode and passing in of secret argument

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#19]
Should support passing in of secret argument.

Automatically attempt to go into enable mode if secret argument is present.

**Comment by ktbyers** [comment]
The solution for this is staged pending the release of Netmiko 1.0 which come out this week  (week of 9/12)

**Comment by ktbyers** [comment]
Fix in develop branch.

**Comment by nickermire** [comment]
I'm also having this problem when calling napalm via ansible. Had to set privilege mode to 15 for the module to work. Netmiko version is 1.1.0.

Here is my playbook.yml
` - name: Push config to switch group.
  hosts: test 
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname={{ inventory_hostname }}
        username=theusername
        dev_os=ios
        password=thepassword
        secret=thesecret
        filter='interfaces'
      register: result

```
- debug: msg= "{{ result.stdout }}"`
```

**Comment by nickermire** [comment]
Also have to delete the secret variable as it breaks the playbook.

**Comment by ktbyers** [comment]
@nickermire You need to file your issue against napalm-ansible. That is the the more logical place for it. This above issue has been fixed, napalm-ios now supports all Netmiko arguments.

**Comment by nickermire** [comment]
Thanks Kirk
