### ISSUE TITLE
Cannot install config if candidate change username

### ISSUE THREAD

**Issue by targuan** [napalm-automation/napalm-ios#215]
### Description of Issue/Question
When the candidate configuration change an username, the configuration replace ask for a confirmation:
```
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
```
load_replace_candidate hangs and fails to complete.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
-e git+https://github.com/napalm-automation/napalm-ios@8cf5d607a5b8e285d505c6827f828f659ca3d781#egg=napalm_ios
```

### IOS version
(Paste verbatim output from `show version` between quotes below)

```
Version 03.06.06E
```

### Steps to Reproduce the Issue
load_replace_candidate a configuration that has different username than those defined in the running

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
cannot install config: Search pattern never detected in send_command_expect: [>##]\\s*$
```

**Comment by mirceaulinic** [comment]
Hi @targuan - we are currently in the process of reunification, please check https://napalm-automation.net/reunification/.
For the time being, we have moved this issue to https://github.com/napalm-automation/napalm/issues/471 so we can discuss further.
Going forward, we'd like to ask you to submit Pull Requests and Issues to the main repository: https://github.com/napalm-automation/napalm

Thanks for understanding!
