### ISSUE TITLE
Changes before Hackathon

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#31]
@dbarrosop @mirceaulinic 

I have staged some changes to napalm-ios prior to the Hackathon. I am planning on submitting these once I release Netmiko 1.0 which should be before Thursday.

Here are the changes I made:
- Adding support to import all Netmiko ConnectHandler arguments. This will add support for SSH keys and for an enable secret.
- Add version to be a part of the package so you can do napalm_ios.__version__ (i.e. so you clearly check which version of the code you are running).
- Eliminate PEP257 from pylama.ini (basically want ios.py to 100% pass pylama and PEP257 is too pedantic. I also excepted C901 (McCabe too complex rule). I would rather have fewer rules but require compliance, than more rules and ignore warnings/issues.
- Fixed issues on get_lldp_neighbors_detail, get_snmp_information, get_mac_address_table that was causing them all to fail when I tested against a real IOS router.
- Rolled Netmiko requirement to 1.0.

Changes are here:
https://github.com/ktbyers/napalm-ios/tree/devel

Some of these might conflict with other plans you have (particularly pylama.ini changes and setup.py changes) so bringing up here.

**Comment by mirceaulinic** [comment]
I had a brief look in the changes you have in the devel branch - looks good.

> Add version to be a part of the package so you can do napalm_ios.version (i.e. so you clearly check which version of the code you are running).

I'm thinking that we could replicate this across all drivers.

> Some of these might conflict with other plans you have (particularly pylama.ini changes and setup.py changes) so bringing up here.

I would let @dbarrosop speak here - I never worked with pylama (I'm using pylint with very restrictive config, e.g.: https://github.com/mirceaulinic/iosxr-eznc/blob/master/.pylintrc). 
BTW shall we raise this subject in the napalm-council?

**Comment by ktbyers** [comment]
@mirceaulinic FYI, made slight edit above...it was supposed to be:

napalm_ios.__version__

But got modified by the markdown. This is what I typically see for references to __version__

**Comment by dbarrosop** [comment]
I was going to comment inline in the code but that will make it harder to track as there is no PR so there is not a single point of entry so I will just comment here:
- `__version__` - Makes complete sense, I will create issues for all the repos to track this.
- `find_version` - Can we move it to `napalm-base/napalm_base/utils/string_parsers.py` so we can reuse it everywhere?
- Ignoring pep257 - Not so sure about this, I like enforcing docstrings as we enforce code. We can always iterate and enable this things one by one, of course which would make sense, I will create an issue I'd suggest to get rid of the pylama.ini file in this PR and discuss what we want to do and how here: napalm-automation/napalm-base#61

Other than that the branch looks pretty solid : )

**Comment by dbarrosop** [comment]
Issue created: napalm-automation/napalm-base#70

**Comment by ktbyers** [comment]
Done.
