### ISSUE TITLE
napalm-ios is not getting into enable mode if secret is passed

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#63]
'dir' command in the auto detection of the filesystem will fail if not in enable mode, but there is nothing ensuring that the device is in enable mode.

Might also affect panos, ios-xr, and vyos drivers that use Netmiko

**Comment by ktbyers** [comment]
Initial fix didn't work as SCP channel also requires enable() mode. Fixing that might be problematic. Affects config operations not getter operations.

**Comment by dbarrosop** [comment]
do you need some help with this? I can be your rubber duck : )

**Comment by ktbyers** [comment]
Can you use Netmiko InLineTransfer to solve this.

**Comment by dbarrosop** [comment]
do you need me to do something here?

**Comment by ktbyers** [comment]
No...I just need to implement it.

**Comment by ktbyers** [comment]
https://github.com/napalm-automation/napalm-ios/pull/100

optional_args['inline_transfer'] = True

Will cause TCL transfer to occur which uses the main ssh connection (which supports secret argument).
