### ISSUE TITLE
Napalm to Extreme Network devices

### ISSUE THREAD

**Issue by fabbiomcosta** [napalm-automation/napalm-ios#68]
Hello everybody,

Brief introduction:
 I've been studing Ansible and Salt for about a week and I found Napalm library two days ago on the internet.  I tested Napalm with juniper and cisco (works well, amazing). However,  we have almost 90 Extreme Networks switches in our network and they are old devices and with certain limitations, telnet is one of them. I also have a mgtm vlan via telnet to manage them.

So, is it  possible to use napalm for this devices via telnet?

Regards.

**Comment by mirceaulinic** [comment]
Hi @fabbiomcosta 

`napalm-ios` is using `netmiko` (https://github.com/ktbyers/netmiko/tree/master/netmiko) as transport libray. AFAIK netmiko provides now support for telnet - @ktbyers please correct me if I'm wrong. If that's the case, I think we can definitely introduce this feature, via a new optional argument (http://napalm.readthedocs.io/en/latest/support/index.html#optional-arguments). We can then extend this for other drivers as iosxr, junos (as junos-eznc 2.0 introduced telnet support) and maybe others.

**Comment by fabbiomcosta** [comment]
Hi @mirceaulinic, 
I'm not a developer, but i saw that netmiko provides support for telnet. So, you are right. 
How could I help you to deploy the new optional argument? I'm interested in helping this project.

**Comment by ktbyers** [comment]
Netmiko supports telnet using device_type 'cisco_ios_telnet'. Extreme might work using this driver (for Netmiko).

napalm-ios can't be made to work with telnet as configuration file operations all use secure copy to transfer files (at least as currently constructed).

**Comment by dbarrosop** [comment]
@ktbyers how hard would it be to support the getters over telnet? Obviously, if the user decide to use telnet as transport configuration related methods should be disabled.

**Comment by ktbyers** [comment]
@dbarrosop getters is probably easy if the Netmiko 'cisco_ios_telnet' driver just works.

**Comment by dbarrosop** [comment]
I will let you decide if it's worth supporting the getters via telnet. I understand configuration might be trickier.

**Comment by ktbyers** [comment]
I can't bring myself to implement this...if someone else wants to, submit a PR on it. You would just to add an optional_argument to pass in a protocol, telnet or ssh.

Then just switch the device_type from cisco_ios to cisco_ios_telnet.

**Comment by mirceaulinic** [comment]
> You would just to add an optional_argument to pass in a protocol, telnet or ssh.

How does ```transport_type``` sound to you @ktbyers? The reasoning I'm asking is that we could probably offer telnet transport for other drivers as well.

> Then just switch the device_type from cisco_ios to cisco_ios_telnet.

And raise exception for config-related methods? Or something else? - I understand they won't work at all over telnet.
