### ISSUE TITLE
Add support for inline config merge and inline config replace

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#7]
Need support for inline config merge, config replace (i.e. not from an external file, but from inline in-code).

**Comment by dbarrosop** [comment]
If this works, could we completely get rid of the SCP and just load the file the user is passing into a string? That's actually how it works on the rest of the drivers. Files are usually not involved in the communication with the devices.

**Comment by ktbyers** [comment]
Yes, we should leave SCP has the primary mechanism. The Netmiko InLineTransfer is still a file transfer (i.e. writes a file in flash). It also has some file manipulation that goes on to get it work with TCL (i.e. newlines and errors on TCL terminator character). 

Because of this the SCP file transfer mechanism should be the default/preferred and the other mechanism an alternative that can be specified via an optional argument.

**Comment by mirceaulinic** [comment]
> Because of this the SCP file transfer mechanism should be the default/preferred and the other mechanism an alternative that can be specified via an optional argument.

I understand this is very tricky, but I do you mean that someone needs to specify a certain flag in order to be able to use `device.load_merge_candidate(config='my fancy config')`?

A user has to be able to execute both:

- device.load_merge_candidate(config='my fancy config')
- device.load_merge_candidate(filename='/path/to/my/file')

This is the behaviour of the rest of the drivers.

**Comment by ktbyers** [comment]
@mirceaulinic Yes, it will work as required by the NAPALM API i.e. you can do both of these operations:

```
device.load_merge_candidate(config='my fancy config')
device.load_merge_candidate(filename='/path/to/my/file')
```

But by default both of these operations will use Secure Copy.

There will also be a separate optional argument you can specify whereby you can transfer a file completely inside the SSH (or telnet) session using TCL behind the scenes.

This will allow telnet to work and fix the Cisco SCP transfer issue with enable (i.e. that they require a priv 15 account to SCP transfer and you can't do enable).

Does that make sense?

**Comment by mirceaulinic** [comment]
Totally. Thanks very much for explanation! :)

**Comment by ktbyers** [comment]
PR for this here https://github.com/napalm-automation/napalm-ios/pull/100
