### ISSUE TITLE
Improve Cisco IOS unit test

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ios#8]
Update unittests to test that invalid commands in a replace config operation get rejected.

**Comment by ktbyers** [comment]
Add hostname change for merge and replace operation to unit tests.
Add write mem into unit tests.
Update unit tests for merge and compare_config()

**Comment by mirceaulinic** [comment]
@ktbyers after the migration to the new testing framework, does this still present interest? Or is it obsolete?

**Comment by ktbyers** [comment]
Let me review and see if this is done.

**Comment by dbarrosop** [comment]
Still relevant?
