### ISSUE TITLE
`load_template` doesn't work as `load_merge_candidate` does not support `config` arg

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm-ios#98]
### Description of Issue/Question

Looks like `load_merge_candidate` does not accept the `config` arg: https://github.com/napalm-automation/napalm-ios/blob/develop/napalm_ios/ios.py#L170-L171

For this reason, the `load_template` helper won't work as it tries to send the result after the template is renders in the `config` argument:  https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/helpers.py#L86

**Comment by ktbyers** [comment]
See: https://github.com/napalm-automation/napalm-ios/issues/7

**Comment by ktbyers** [comment]
I will see if I can fix this weekend or early next week.

**Comment by mirceaulinic** [comment]
Meanwhile I was already looking at some sort of solution... has been written only by guess.

**Comment by ktbyers** [comment]
How do we want to implement this...I think we should probably use the InLine transfer mechanism (or at least give the option for this).

This would allow people who for some reason can't use SCP (biggest issue being SCP mechanism requires a direct priv15 account i.e. can't do enable with separate SCP channel...Cisco limitation).

So people would have two mechanisms and they could code around to use either (if required), by them reading or writing a file.

**Comment by mirceaulinic** [comment]
@ktbyers you know the best what would be the most suitable.

From the surface I would be tempted to suggest leaving the current behaviour unchanged, provide the ability to use the `config` arg; in addition let the user choose the InLine transfer instead of SCP, by specifying an optional arg as you suggested.

... and I guess I only rephrased what you just said :)

**Comment by ktbyers** [comment]
Fix for this is here:

https://github.com/napalm-automation/napalm-ios/pull/100
